name: Full CI

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    name: Build wheel
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: "18.x"

      - name: Install Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.12"
          architecture: "x64"

      - name: Setup pip cache
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: ~/.cache/pip
          key: pip-3.12-${{ hashFiles('package.json') }}
          restore-keys: |
            pip-3.12-
            pip-

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
      - uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
          
      - name: Build wheel
        run: |
          python -m pip install build
          python -m build --wheel

      - name: Install wheel
        run: pip3 install dist/*.whl --user

      - name: Dev install  # Install in sources in order to do checkings like linting
        run: |
          pip3 uninstall -y pypowsybl_jupyter
          python -m pip install --upgrade -v -e ".[dev]"
          npm run lint

      - name: Upload wheel
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: pypowsybl_jupyter-wheel
          path: dist/*.whl

  package:
    name: Package wheels
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download wheels
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
        with:
          path: download

      - name: Release to PyPi
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          python -m pip install --user --upgrade twine
          python -m twine upload --username __token__ --password ${{ secrets.PYPI_TOKEN }} download/*/*.whl
